version: '3.3'

services:

  ### app
  app:
    image: swissre/tasks-app:latest
    container_name: swissre-app
    networks:
      - swissre-task-app-net
    profiles:
      - app
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=demo
      - DB_USER=root
      - DB_PASSWORD=pass
    ports:
      - "8080:8443"
    depends_on:
      - mysql
    restart: on-failure

  ### MySQL Container
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysqldb
    networks:
      - swissre-task-app-net
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_DATABASE=demo
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - "3306:3306"

networks:
  swissre-task-app-net: